spring:
    datasource:
        url: jdbc:mysql://localhost:3306/teste
        username: root
        password: 1414
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect

api:
    security:
        jwt:
            audience: ${JWT_AUDIENCE:default-petcontrol-audience}
            issuer: ${JWT_ISSUER:default-petcontrol-issuer}
            secret: ${JWT_SECRET:default-petcontrol-secret}
            expiration: ${JWT_EXPIRATION:900000} #15min
            refresh-token:
                expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:1800000} #30min