spring:
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}

api:
    security:
        jwt:
            issuer: ${JWT_ISSUER}
            secret: ${JWT_SECRET}
            expiration: ${JWT_EXPIRATION}