spring:
    datasource:
        url: jdbc:mysql://localhost:3306/teste
        username: root
        password: 1414
    jpa:
        hibernate:
            ddl-auto: create

api:
    security:
        jwt:
            issuer: ${JWT_ISSUER:default-petcontrol-issuer}
            secret: ${JWT_SECRET:default-petcontrol-secret}
            expiration: ${JWT_EXPIRATION:60000}