spring:
    datasource:
        url: jdbc:mysql://localhost:3306/teste
        username: root
        password: 1414
    jpa:
        hibernate:
            ddl-auto: update

api:
    security:
        token:
            secret: ${JWT_SECRET:default-secret-key}