spring:
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}

api:
    security:
        jwt:
            audience: ${JWT_AUDIENCE}
            issuer: ${JWT_ISSUER}
            secret: ${JWT_SECRET}
            expiration: ${JWT_EXPIRATION}
            refresh-token:
                expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}