spring:
    datasource:
        url: jdbc:mysql://localhost:3306/teste
        username: root
        password: 1414
    jpa:
        hibernate:
            ddl-auto: create

api:
    security:
        jwt:
            audience: default-petcontrol-audience
            issuer: default-petcontrol-issuer
            secret: default-petcontrol-secret
            expiration: 300000 #5min
            refresh-token:
                expiration: 600000 #10min